import { types } from './types.js'

export const {
  DONG_RECEIVED_EVENT,
  ERROR_RECEIVED_EVENT,
  FRIENDSHIP_RECEIVED_EVENT,
  HEARTBEAT_RECEIVED_EVENT,
  LOGIN_RECEIVED_EVENT,
  LOGOUT_RECEIVED_EVENT,
  MESSAGE_RECEIVED_EVENT,
  READY_RECEIVED_EVENT,
  RESET_RECEIVED_EVENT,
  ROOM_INVITE_RECEIVED_EVENT,
  ROOM_JOIN_RECEIVED_EVENT,
  ROOM_LEAVE_RECEIVED_EVENT,
  ROOM_TOPIC_RECEIVED_EVENT,
  SCAN_RECEIVED_EVENT,
  STARTED_EVENT,
  STATE_ACTIVATED_EVENT,
  STATE_INACTIVATED_EVENT,
  STOPPED_EVENT,
} = types
