import { types } from './types.js'

export const {
  GET_AUTH_QR_CODE_QUERY,
  GET_CURRENT_USER_ID_QUERY,
  GET_IS_LOGGED_IN_QUERY,
  GET_MESSAGE_PAYLOAD_QUERY,
  GET_SAYABLE_PAYLOAD_QUERY,
} = types
